apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-access-location-location
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-access-network-location
              image: cloudflare-access-network-location
              envFrom:
                - secretRef:
                    name: cloudflare-access-network-location
          restartPolicy: OnFailure