name: Docker Image CI - Publish Private

on:
  push:
    branches: [ main, master ]
    paths-ignore:
        - 'README.md'
        - 'LICENSE'
        - 'CONTRIBUTING.md'
        - 'CODE_OF_CONDUCT.md'
        - '.github/**'
        - 'manifests/**'
  workflow_dispatch:
    

jobs:

  build:

    runs-on: self-hosted,x64

    steps:
    - uses: actions/checkout@v4
      name: Checkout Repo Code

    - uses: docker/login-action@v3.0.0
      with:
        registry: ${{ secrets.DOCKER_REPOSITORY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host      

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY }}/east/${{ secrets.IMAGE_NAME }}:latest
        
    - uses: 8398a7/action-slack@v3
      name: Slack Notification
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
