name: Docker Image CI - Publish Private

on:
  push:
    branches: [ main, master ]
    paths-ignore:
        - 'README.md'
        - 'LICENSE'
        - 'CONTRIBUTING.md'
        - 'CODE_OF_CONDUCT.md'
        - '.github/**'
        - 'manifests/**'
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  actions: read
  
jobs:
  build:
    runs-on: gallis-gh-runner
    steps:
    - uses: actions/checkout@v5
      name: Checkout Repo Code

    - name: Setup HashiCorp Vault
      uses: hashicorp/vault-action@v3
      with:
        url: ${{vars.VAULT_ADDR}}
        method: jwt
        role: github-actions-role
        path: github-actions
        secrets: |
          prod-kubernetes/data/harbor/arm registry-name | HARBOR_NAME ;          
          prod-kubernetes/data/harbor/arm registry-library | HARBOR_LIBRARY ;
          prod-kubernetes/data/harbor/arm github-actions-robot-username | HARBOR_USERNAME ;
          prod-kubernetes/data/harbor/arm github-actions-robot-password | HARBOR_PASSWORD ;
          prod-kubernetes/data/github/slack-webhooks slack-repo-channel | SLACK_WEBHOOK_URL ;

    - uses: docker/login-action@v3.5.0
      with:
        registry: ${{ env.HARBOR_NAME }}
        username: ${{ env.HARBOR_USERNAME }}
        password: ${{ env.HARBOR_PASSWORD }}

    - name: Install QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host      

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.HARBOR_NAME }}/${{ env.HARBOR_LIBRARY }}/${{ vars.IMAGE_NAME }}:latest

    - uses: 8398a7/action-slack@v3
      name: Slack Notification
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      #env:
        #SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
